# Generated by Django 4.1.2 on 2022-11-17 07:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name': 'Скидка', 'verbose_name_plural': 'Скидки'},
        ),
        migrations.AlterModelOptions(
            name='tax',
            options={'verbose_name': 'Налог', 'verbose_name_plural': 'Налоги'},
        ),
        migrations.AddField(
            model_name='discount',
            name='discount_rate',
            field=models.CharField(default='0', max_length=5, validators=[django.core.validators.RegexValidator(message='проверка процентов скидки', regex='^0*(100\\.00|[0-9]?[0-9]\\.[0-9]{2})%$')], verbose_name='Размер скидки'),
        ),
        migrations.AddField(
            model_name='tax',
            name='tax_rate',
            field=models.CharField(default='0', max_length=5, validators=[django.core.validators.RegexValidator(message='проверка процентов налога', regex='^0*(100\\.00|[0-9]?[0-9]\\.[0-9]{2})%$')], verbose_name='Размер налога'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Цена'),
        ),
    ]
