# Generated by Django 4.1.2 on 2022-11-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_order_discounts_alter_order_taxes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('RUB', 'RUB'), ('USD', 'USD')], default='RUB', max_length=3),
        ),
    ]
